/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalInput: typeof import('./src/components/GlobalInput.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Slider: typeof import('./src/components/slider.vue')['default']
    Tab: typeof import('./src/components/tab.vue')['default']
    Toobar: typeof import('./src/components/toobar.vue')['default']
    ToolbarItem: typeof import('./src/components/ToolbarItem.vue')['default']
  }
}
